env=XDG_CURRENT_DESKTOP,mango
env=XDG_SESSION_TYPE,wayland
env=QT_QPA_PLATFORM,wayland
env=GDK_BACKEND,wayland,x11
gappih=6
gappoh=6
borderpx=3
focuscolor=0xc9b890ff
unfocuscolor=0x444444ff
blur=1
shadows=1
border_radius=8
focused_opacity=1.0
unfocused_opacity=0.85
animations=1
animation_type_open=slide
animation_duration_open=400
animation_type_close=fade
animation_duration_close=300
xkb_rules_layout=us
repeat_rate=25
repeat_delay=600
tap_to_click=1
mouse_natural_scrolling=0
click_method=2
bind=ALT,r,reload_config
bind=ALT,m,quit
bind=ALT,Return,spawn,foot
bind=ALT,space,spawn,bemenu-run
bind=ALT,q,killclient
bind=ALT,h,movefocus,l
bind=ALT,l,movefocus,r
bind=ALT,k,movefocus,u
bind=ALT,j,movefocus,d
bind=ALT,y,toggle_fullscreen
bind=ALT,Backslash,toggle_floating
bind=ALT,x,nextlayout
bind=ALT,1,view,1
bind=ALT,2,view,2
bind=ALT,3,view,3
bind=ALT,4,view,4
bind=ALT,5,view,5
